apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: department-service-destination-rule  
  namespace: default  
spec:
  host: department-service
  subsets:
  - name: v1
    labels:
      version: v1