apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: department-service
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  # Users API: /department/departments -> /v1/departments (default to v1)
  - match:
    - uri:
        prefix: /department/departments
    rewrite:
      uri: /v1/departments
    route:
    - destination:
        host: department-service
        subset: v1