apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/migration.sql
              subPath: migration.sql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.name }}
        - name: init-script
          configMap:
            name: {{ .Values.configMap.name }}
            items:
              - key: migration.sql
                path: migration.sql
