apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ Values.postgres.pvcName" }}
  labels:
spec:
  accessModes:
    {{.Values.postgresql.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize }}