apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword }}
  POSTGRES_DB: {{ .Values.secret.postgresDB }}
