apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.secretName }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.usernameKey }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.passwordKey }}
  POSTGRES_DB: {{ .Values.postgresql.databaseKey }}