apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: postgres
  ports:
    - name: tcp-postgres
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
