replicaCount: 1

image:
  repository: department-service
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8185

configMap:
  name: all-service-config

secret:
  name: all-service-secret

zapConfigMap:
  name: zap-logger-config

gormConfigMap:
  name: gorm-logger-config

service:
  type: NodePort
  port: 5002

ingress:
  enabled: false

resources: {}