apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: user-service
    release: prometheus  
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 8185

