apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: user-service
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  # 1. If header x-user-type: beta is present, route to v2
  - match:
    - uri:
        prefix: /user/users
      headers:
        x-user-type:
          exact: beta
    rewrite:
      uri: /v2/users
    route:
    - destination:
        host: user-service
        subset: v2
  # 2. Otherwise, route to v1 (default)
  - match:
    - uri:
        prefix: /user/users
    rewrite:
      uri: /v1/users
    route:
    - destination:
        host: user-service
        subset: v1
