apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-gateway
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  # Users API: /user/users -> /v1/users (default to v1)
  - match:
    - uri:
        prefix: /user/users
    rewrite:
      uri: /v1/users
    route:
    - destination:
        host: user-service
        subset: v1

