apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  gateways:
    - app-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /user/
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}

