apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}
spec:
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgresql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.name }}
    spec:
      containers:
        - name: {{ .Values.postgresql.name }}
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: {{ .Values.postgresql.servicePort }}
          envFrom:
            - secretRef:
                name: {{ .Values.postgresql.secretName }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/migration.sql
              subPath: migration.sql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.postgresql.pvcName }}
        - name: init-script
          configMap:
            name: {{ .Values.postgresql.initScript.configMapName }}
            items:
              - key: migration.sql
                path: migration.sql
