apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.postgresql.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.postgresql.servicePort }}
      targetPort: {{ .Values.postgresql.servicePort }}
