apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}

