apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  gateways:
    - mesh
  hosts:
    - point-service.default.svc.cluster.local
  tcp:
    - match:
        - port: {{ .Values.service.port }}
      route:
        - destination:
            host: point-service.default.svc.cluster.local
            port:
              number: {{ .Values.service.port }}

